# Generated by Django 5.2 on 2025-04-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='number_member',
            field=models.IntegerField(default=0),
        ),
    ]
